<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerT1z2vtv\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerT1z2vtv/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerT1z2vtv.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerT1z2vtv\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerT1z2vtv\srcDevDebugProjectContainer([
    'container.build_hash' => 'T1z2vtv',
    'container.build_id' => '0fcad11d',
    'container.build_time' => 1566216053,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerT1z2vtv');
