<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXl9xfqk\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXl9xfqk/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerXl9xfqk.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerXl9xfqk\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerXl9xfqk\srcDevDebugProjectContainer([
    'container.build_hash' => 'Xl9xfqk',
    'container.build_id' => 'df16c83e',
    'container.build_time' => 1566220826,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXl9xfqk');
